name: .deb builds

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true

jobs:
  ubuntu:
    name: "Ubuntu 24.04 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
          - arch: amd64
            runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: ubuntu

  debian-13:
    name: "Debian 13 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    container: ghcr.io/nilcons/debian:latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
          - arch: amd64
            runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: debian-13

  debian-12:
    name: "Debian 12 (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    container: ghcr.io/xrplf/ci/debian-bookworm:gcc-12
    strategy:
      fail-fast: false
      matrix:
        os:
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
          - arch: amd64
            runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Package
        uses: ./.github/workflows/debian
        with:
          arch: ${{ matrix.os.arch }}
          name: debian-12

