name: "Linux"

on:
  workflow_call:
    inputs:
      build-id:
        description: 'Identifier for workflows and caching'
        type: string
        required: true
      cpm-cache-version:
        description: 'CPM Cache Version'
        type: string
        required: true
      devel:
        description: 'Development mode (disables update checker)'
        type: string
        required: true
      force_pgo:
        description: 'Force PGO builds'
        type: string
        required: true
      matrix:
        description: 'Generated Matrix to each platform'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  linux:
    name: "${{ matrix.compiler.pretty-name }} ${{ matrix.compiler.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    runs-on: ${{ matrix.compiler.runs-on }}
    container:
      image: ${{ matrix.compiler.container }}
      options: --privileged --device /dev/fuse -v "${{ github.workspace }}":"${{ github.workspace }}"
    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJson(inputs.matrix) }}

    env:
      TARGET: "${{ matrix.compiler.arch }}"
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      FULL_ARCH: ${{ matrix.compiler.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install dependencies
        if: ${{ matrix.compiler.system == 'linux' }}
        run: ./.ci/linux/deps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.compiler.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Configure
        if: ${{ matrix.compiler.system == 'linux' }}
        run:  .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        if: ${{ matrix.compiler.system == 'linux' }}
        run: cmake --build build

      - name: Package
        if: ${{ matrix.compiler.system == 'linux' }}
        run: ./.ci/linux/package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload artifacts
        if: ${{ matrix.compiler.id == 'linux' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: linux-${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}
          path: ./artifacts/*.AppImage*

      - name: Build
        if: ${{ matrix.compiler.id == 'debian' }}
        run: ./.ci/debian/makedeb.sh
        env:
          ARCH: ${{ matrix.compiler.arch }}
          DEB_NAME: ${{ matrix.compiler.pretty-name }}

      - name: Upload artifacts
        if: ${{ matrix.compiler.id == 'debian' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.compiler.system }}-${{ matrix.compiler.arch }}
          path: ./artifacts/*.deb
