name: Create Tag Release

on:
  repository_dispatch:
    types: [tag]

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-type: 'Release'
      devel: false
      build-id: 'tag'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Load payload environment
        shell: bash
        run: |
          ./.ci/forgejo-ci.sh --load-payload-env

      - name: Set environment variables
        run: |
          echo "REPO=eden-emulator/Releases" >> $GITHUB_ENV
          echo "DEVEL=false" >> $GITHUB_ENV

          case "${{ env.FORGEJO_REF }}" in
            (*rc*|*alpha*|*beta*)
              echo "TRACK=beta" >> $GITHUB_ENV
              ;;
            (*)
              echo "TRACK=production" >> $GITHUB_ENV
              ;;
          esac

      - name: Package artifacts nicely
        run: |
          export ID=${FORGEJO_REF}
          ./pack.sh

      - name: Generate changelog(s)
        run: |
          ./.ci/changelog/generate.sh tag > changelog.md
          mkdir -p whatsnew
          echo "See the changelog here: https://github.com/eden-emulator/Releases/releases/tag/${{ env.FORGEJO_REF }}" > whatsnew/whatsnew-en-US

      # - uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.PLAY_CREDENTIALS }}
      #     packageName: dev.eden.eden_emulator
      #     track: ${{ env.TRACK }}
      #     releaseFiles: android-aab/*.aab
      #     whatsNewDirectory: whatsnew
      #     releaseName: ${{ env.FORGEJO_REF }}

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden ${{ env.FORGEJO_REF }}"
          tag_name: ${{ env.FORGEJO_REF }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: true
          generate_release_notes: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*
