name: "- Pull Request/Test Build Workflow"

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-id: 'test'
    secrets: inherit
